import Head from "next/head";
import styles from "../styles/Home.module.css"
import ImageDesc  from "./components/ImageDesc";

import { useEffect , useState } from "react";

export default function Home() {


    const [listesChampions  , setlistesChampions] = useState([]);
    

    useEffect(() => {
      getCards();
    }, []);  // Appelle la fonction getCards au chargement de la page

    

    const getCards = () => {
      fetch("http://localhost:3001/cards")
        .then(response => {
          if (!response.ok) {
            throw new Error("HTTP error " + response.status);
          }
          return response.json(); // Convertit la réponse en JSON
        })
        .then( data => {
                        console.log(data)
                        setlistesChampions(data)
                      }) // Affiche les données reçues
        .catch(error => console.error("Error:", error)); // Capture les erreurs
    };
     
    
    

  return (
    <>
      <Head>
        <title>League of Stones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className= {styles.body} >
        <main >
          <section className= {`${styles.tousLesCards} , "row" `} >
              <section className= {`${styles.lesCards}, "col" offset-6`}> 
                  {listesChampions.map((card, index) =>  <ImageDesc key={index} desc={card} />) }
              </section>

              <section className= {`${styles.lesCardsSelectionnes}, "col" offset-6`}><h1>Ici les cartes selectionnées</h1></section>
          </section>
        </main>
      </section>
    </>
  );


}